### PR TITLE
Fix Enemy Filter.

### LINKED ISSUE #847: Enemy Filter not working after page rework
Since the enemy page rework, the filter no longer works. 

Biggest changes:
- new url
- completely different html structure
- infinite scrolling instead of paginated
- native filters + sorting

What needs to be done:
- show filter on the new page
- remove the status filter
- filter based on the new structure
- apply filter when the list changes due to
  - scrolling  
  - native filter
  - native sort
- keep compatibility with 'Stats Estimate'

Recommended to look at the faction member list filter.

### LINKED ISSUE #848: Stats Estimates not working on the enemies page after rework
Since the enemy page rework, the stat estimates no longer works. 

Biggest changes:
- new url
- completely different html structure
- infinite scrolling instead of paginated
- native filters + sorting

What needs to be done:
- load estimated based on thew new layout
- compatibility with native filtering and sorting
- load more estimates on scroll
- keep compatibility with 'Enemy Filter'

Recommended to look at the last action feature on the faction member list.

### PR DESCRIPTION
**Pull request by Sashank999**
Closes #847.
Closes #848.

### CODE REVIEW

File: extension/scripts/features/enemy-filter/ttEnemyFilter.js [hunk 1]
```diff
@@ -28,32 +29,38 @@
...
 
-			new MutationObserver((mutations, observer) => {
-				addFilters();
-				observer.disconnect();
-			}).observe(document.find(".blacklist"), { childList: true });
+		const tableObserver = new MutationObserver((mutations) => {
+			if (mutations.some((mutation) => [...mutation.addedNodes].some((node) => node.tagName === "UL"))) {
+				if (filterSetupComplete && feature.enabled()) {
+					applyFilters(true);
+					listObserver.observe(document.find(".tableWrapper > ul"));
```
Comment (DeKleineKobini) [inline extension/scripts/features/enemy-filter/ttEnemyFilter.js:44]: Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': The options object must set at least one of 'attributes', 'characterData', or 'childList' to true.

File: extension/scripts/features/stats-estimate/ttStatsEstimateEnemies.js [hunk 2]
```diff
@@ -19,30 +19,36 @@
...
+				if (feature.enabled())
+					showEstimates();
+			}
 		});
+
+		const tableObserver = new MutationObserver((mutations) => {
+			if (mutations.some((mutation) => [...mutation.addedNodes].some((node) => node.tagName === "UL"))) {
+				if (feature.enabled()) {
+					showEstimates();
+					listObserver.observe(document.find(".tableWrapper > ul"));
```
Comment (DeKleineKobini) [inline extension/scripts/features/stats-estimate/ttStatsEstimateEnemies.js:34]: Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': The options object must set at least one of 'attributes', 'characterData', or 'childList' to true.

**Review by DeKleineKobini — CHANGES_REQUESTED** [review]
Just missing the changelog entries now. I would split it into 2, as you fixed 2 features.
