### PR TITLE
#241 Fix

### LINKED ISSUE #241: [BUG] Show full faction description is broken.
**Describe the bug**
Show full faction description doesn't work anymore.

**Screenshots**
Screenshot

**Additional context**
It's only an issue on faction descriptions, not announcements.

### PR DESCRIPTION
**Pull request by Sashank999**
Closes #241 .

### CODE REVIEW

**Comment by Sashank999** [comment]
Previously :
The _Show full page_ feature works on user's own faction's page but not on other faction's pages.
After 1st bug fix :
The _Show full page_ feature doesn't work on user's own faction's page but works on other faction's pages.
After 2nd bug fix :
The _Show full page_ feature works on both user's own faction's page and on other faction's pages.

File: torntools/scripts/content/faction/ttFaction.js [hunk 1]
```diff
@@ -417,15 +417,18 @@ function showNNB() {
...
 	if (getSearchParameters().get("step") === "profile") {
 		info_box = doc.find("#factions div[data-title='description']").nextElementSibling;
 	} else if (page === "main") {
 		info_box = doc.find("div[data-title='announcement']").nextElementSibling;
+		facDescription = info_box;
 	} else if (page === "info") {
 		info_box = doc.find("#faction-info .faction-info-wrap.faction-description .faction-info");
 	}
 
+	facDescription ? facDescription = info_box : facDescription = info_box.parentElement.find("div.faction-description");
```
Comment (DeKleineKobini) [inline torntools/scripts/content/faction/ttFaction.js:430]: It would be better to do `facDescription = x ? a : b` directly. It's shorter and more clear at first glance.

**Review by DeKleineKobini — APPROVED** [review]

**Review by DeKleineKobini — CHANGES_REQUESTED** [review]
Didn't mean to approve the previous review.

**Comment by DeKleineKobini** [comment]
Since I want to release 5.6 asap, I've fixed it myself.
