### PR TITLE
Small reload for fix #297

### LINKED ISSUE #297: [BUG] Clear targets button
**Describe the bug**
Clear targets button not working correctly, function might be broken.

### PR DESCRIPTION
**Pull request by Sashank999**
Closes #297 .

### CODE REVIEW

File: torntools/views/settings/settings.js [hunk 1]
```diff
@@ -70,6 +70,7 @@ requireDatabase(false)
 				},
 			});
 			message("Target list reset.", true);
+			location.reload();
```
Comment (DeKleineKobini) [inline torntools/views/settings/settings.js:73]: `message("Target list reset.", true, {reload: true });` does the same, but with a delay so they can read the message first.

Comment (Sashank999) [reply torntools/views/settings/settings.js]: Done.

**Review by DeKleineKobini — APPROVED** [review]
